### PR TITLE
arm64: add support for libusb0 on arm64

### PR DESCRIPTION
**Pull request by dontech**
A few patches to add more ARM64 support for libwdi

### CODE REVIEW

**Comment by dontech** [comment]
Fixed the missing files in the workflow

**Comment by pbatard** [comment]
Thanks for this PR. The one problem I have with it is that I don't think I want to apply the last patch because it references a non-official release of libusb-win32. Libwdi and especially Zadig provides links to the SourceForge directory, and the latest official release there is still 1.2.7.3 so as long as it remains that way, I don't see myself embedding files (and a version of libusb-win32) that people who click on the libusb-win32 link in Zadig will not find under official releases.

@mcuee, do you guys plan to publish an **official** release of libusb-win32 with the ARM64 drivers at some stage?

**Comment by mcuee** [comment]
@pbatard 

Yes, hopefully we do not have new issues and soon 1.4.0 official release will come out.
* https://github.com/mcuee/libusb-win32/issues/26#issuecomment-1953336677

**Comment by pbatard** [comment]
Okay, then I'll wait for the 1.4.0 release then (which I don't mind, as I'm afraid this patchset is still low priority for me, but I'll try to get through this over the next couple of months).

**Comment by dontech** [comment]
OK i will release 1.4.0 now

**Comment by dontech** [comment]
https://github.com/mcuee/libusb-win32/releases/tag/release_1.4.0.0

**Comment by dontech** [comment]
Please tell me if anything else is blocking this PR

**Comment by mcuee** [comment]
@dontech 

I think @pbatard prefer to use Sourceforge download link. Please upload 1.4.0.0 there as well. Thanks.
https://sourceforge.net/projects/libusb-win32/files/libusb-win32-releases/

**Comment by dontech** [comment]
We have not uploaded there in a while, and I would prefer not to, as it would signal that SF site was still alive, which it is not. And why would libwdi prefer to download form SourceForge when it itself is hosted on github?

**Comment by mcuee** [comment]
Yes I also prefer to use github.

@pbatard Is that okay for you? Thanks.

**Comment by dontech** [comment]
I updated the libusb0 reference to 1.4.0.0 so we should be GTG! :+1:

**Comment by pbatard** [comment]
Could you please sort out a single site then?

From the standpoint of __users__ having to juggle multiple sites is not ideal. So, if you want to ditch SourceForge, and are clearly planning to leave a download section there with __obsolete__ releases (which is going to be super confusing for users if you state that SourceForge is more or less still active), could you please make one GitHub URL the new official one?

**Comment by mcuee** [comment]
Okay, we will put a note telling the user to go to github.

**Comment by mcuee** [comment]
Done.
https://sourceforge.net/projects/libusb-win32/

Screenshot 2024-02-23 190825
Screenshot 2024-02-23 190904
Screenshot 2024-02-23 190933

**Comment by pbatard** [comment]
Appreciated, thanks.

**Comment by mcuee** [comment]
@pbatard 
libusb-win32 1.4.0 has been released for a while, is it possible that you apply this PR? Thanks.

**Comment by pbatard** [comment]
I'm not sure I'll have much time for libwdi before the Rufus 4.5 release, which is still about 3 weeks away, but I'll see what I can do.

**Comment by pbatard** [comment]
Applied. Sorry it took so long...

**Pull request closed without merging**
