### PR TITLE
Add appveyor artifacts

### PR DESCRIPTION
**Pull request by Jesus89**

### CODE REVIEW

**Comment by pbatard** [comment]
I'm afraid I don't want to do that, as any Windows app that runs elevated should be digitally signed, and if I start making unsigned artifacts officially available on the project, then I am going to __lower__ the global trust people can have when running Zadig.

Running non digitally signed elevated apps has long ceased to be okay, so as a security oriented person, I cannot see myself endorsing any practice that would produce such things. REJECTED.

**Comment by Jesus89** [comment]
Ok. I understand that.

Btw, where can I find official wdi-simple.exe binaries?

**Comment by pbatard** [comment]
I'm afraid I don't provide any, as I estimate that, unlike Zadig, the only people who need it are people who should be able to recompile their own (and sign it, or embed it in a digitally signed app if they plan to publicly redistribute it). 

Also, unlike Zadig, wdi-simple is just a __sample__ of what libwdi can be used for, and therefore not meant to be distributed as a standalone app.

**Comment by Jesus89** [comment]
Ok. Thanks.

**Pull request closed without merging**
